AA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('', include('clients.urls')),
    path('', include('jobs.urls')),
    path('', include('candidates.urls')),
    path('', include('dashboard.urls')),
    path('', include('reports.urls')),
    path('', include('interviews.urls')),
    path('', include('emailclient.urls')),
    path('', include('naukri.urls')),
    path('', include('settings.urls')),
    path('', include('jobportal.urls')),
]

candidates/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [ 
    path('candidates/', views.candidates, name='candidates'),
    path('candidates/add/', views.add_candidate, name='add_candidate'),
    path('candidates/edit/<int:candidate_id>/', views.edit_candidate, name='edit_candidate'),
    path('candidates/delete/', views.delete_candidate, name='delete_candidate'),
    path('candidates/<int:candidate_id>/', views.candidate_details, name='candidate_details'),
    path('submit-candidate/<int:candidate_id>/', views.submit_candidate_to_job, name='submit_candidate_to_job'),
    path('update_submission_stage/<int:submission_id>/', views.update_submission_stage, name='update_submission_stage'),
    path('candidates/import/', views.import_candidate, name='import_candidate'),
    path('submit_candidate_for_job/<int:job_id>/', views.submit_candidate_for_job, name='submit_candidate_for_job'),
    path('submissions/', views.display_submissions, name='display_submissions'),
    path('export_submissions/', views.export_submissions, name='export_submissions'),
 

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candidates/models.py
from django.db import models
from django.conf import settings 
from django.db import models

class Candidate(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=200)
    cv = models.FileField(upload_to='CV_All/')
    location = models.CharField(max_length=200, blank=True, null=True)
    current_ctc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    expected_ctc = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    notice_period = models.PositiveIntegerField(help_text="In days", blank=True, null=True)
    serving_notice_period = models.BooleanField(default=False, blank=True, null=True)
    last_working_day = models.CharField(max_length=200, blank=True, null=True)
    expected_joining_date = models.CharField(max_length=200, blank=True, null=True)
    total_experience = models.PositiveIntegerField(help_text="In years", blank=True, null=True)
    relevant_experience = models.PositiveIntegerField(help_text="In years", blank=True, null=True)
    reason_for_change = models.CharField(max_length=200, blank=True, null=True)
    linkedin_url = models.CharField(max_length=200, blank=True, null=True, default=None)
    recruiter_notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    SOURCE_CHOICES = [
        ('recruiter', 'Sourced'),
        ('application', 'Incoming'),
    ]
    source = models.CharField(
        max_length=20,
        choices=SOURCE_CHOICES, 
        default='recruiter',  
    )

    def __str__(self):
        return self.name

jobs/models.py
from django.db import models
from clients.models import Client
from candidates.models import Candidate
from django.utils import timezone 


class Job(models.Model):
    JOB_TYPE_CHOICES = [
        ('FT', 'FT'),
        ('Cont', 'Con'),
        ('C2H', 'C2H'),
    ]
    JOB_STATUS_CHOICES = [
        ('Open', 'Open'),
        ('Closed', 'Closed'),
        ('Hold', 'Hold'),
        ('Upcoming', 'Upcoming'),
    ]
    MODE_CHOICES = [
        ('Hybrid', 'Hybrid'),
        ('Remote', 'Remote'),
        ('Onsite', 'Onsite'),
    ]
    PRIORITY_CHOICES = [
        ('High', 'High'),
        ('Medium', 'Medium'),
        ('Low', 'Low'),
    ]
    id = models.AutoField(primary_key=True)
    job_title = models.CharField(max_length=100)
    job_description = models.TextField()
    job_notes = models.TextField()
    job_location = models.CharField(max_length=100)
    job_mode = models.CharField(max_length=20, choices=MODE_CHOICES)
    job_status = models.CharField(max_length=20, choices=JOB_STATUS_CHOICES, default='Open')  
    job_work_hours = models.TextField()
    job_type = models.CharField(max_length=20, choices=JOB_TYPE_CHOICES)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    job_priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    job_attachment = models.FileField(upload_to='job_attachments/', blank=True, null=True)
    job_minimum_experience = models.PositiveIntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    candidates = models.ManyToManyField(Candidate, through='JobSubmission')

    def __str__(self):
        return self.job_title



    
from user_management.models import CustomUser

from jobs.models import Job
class JobSubmission(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    date_submitted = models.DateTimeField(auto_now_add=True)
    date_client_submitted = models.DateTimeField(blank=True, null=True)
    previous_stage = models.CharField(max_length=255, blank=True, null=True)
    
    class Meta:
        unique_together = ('job', 'candidate') 
    
    STAGE_CHOICES = [
        ('Internal', 'Internal'),
        ('Client Submission', 'Client Submission'),
        ('QC Reject', 'QC Reject'),
        ('L1 Interview', 'L1 Interview'),
        ('L2 Interview', 'L2 Interview'),
        ('L3 Interview', 'L3 Interview'),
        ('Interview Reject', 'Interview Reject'),
        ('Shortlisted', 'Shortlisted'),
        ('Joined', 'Joined')
    ]
    
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='Internal')
    stage_changed_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.candidate.name}"



from django.shortcuts import redirect, get_object_or_404
from .models import JobSubmission

def update_submission_stage(request, submission_id, stage):
    print(f"Updating stage for submission ID {submission_id} to {stage}")
    submission = get_object_or_404(JobSubmission, id=submission_id)
    if submission.stage != stage:  # Check if the stage is actually changing
        print(f"Stage is changing from {submission.stage} to {stage}")
        submission.stage = stage
        submission.save()
        JobSubmissionHistory.objects.create(
            job_submission=submission,
            stage=stage,
            changed_at=timezone.now()  # Record the current time
        )
    return redirect('job_details', job_id=submission.job.id)


from django.db import models
from django.utils import timezone

class JobSubmissionHistory(models.Model):
    job_submission = models.ForeignKey(JobSubmission, related_name='histories', on_delete=models.CASCADE)
    stage = models.CharField(max_length=20)
    changed_at = models.DateTimeField()
    

    def __str__(self):
        return f"Changed to {self.stage} at {self.changed_at}"
    

candidates/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Candidate
from jobs.models import JobSubmission
from .forms import CandidateForm
from django.db.models import Q 
from django.core.paginator import Paginator
from django.utils import timezone 
from datetime import datetime, timedelta
from user_management.models import CustomUser


def candidates(request):
    query = request.GET.get('q', '')
    recruiter = request.GET.get('recruiter', '')

    date_range = request.GET.get('date_range', '')
    source_filter = request.GET.get('source_filter', '') 

    candidates = Candidate.objects.all()

    if query:
        candidates = candidates.filter(Q(name__icontains=query) | Q(email__icontains=query))

    if date_range:
        try:
            start_date_str, end_date_str = date_range.split(' to ')
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d')
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d') + timedelta(days=1)
            
            start_date = timezone.make_aware(start_date)
            end_date = timezone.make_aware(end_date)

            candidates = candidates.filter(created_at__range=(start_date, end_date))
        except ValueError:
            pass  # Handle the error

    if recruiter:
        candidates = candidates.filter(user__name__icontains=recruiter)

    if source_filter:
        if source_filter == 'sourced':
            candidates = candidates.filter(source='recruiter')
        elif source_filter == 'incoming':
            candidates = candidates.filter(source='application')

    candidates = candidates.order_by('-created_at')



    paginator = Paginator(candidates, 20)
    page_number = request.GET.get('page')
    candidates_page = paginator.get_page(page_number)

    context = {
        'candidates': candidates_page,
        'search_query': query,
        'date_range': date_range,
        'recruiter': recruiter,
    }

    return render(request, 'candidates.html', context)



from django.contrib import messages
def add_candidate(request):
    if request.method == 'POST':
        form = CandidateForm(request.POST, request.FILES)
        if form.is_valid():
            email = form.cleaned_data['email']  # Get email from the form
            existing_candidate = Candidate.objects.filter(email=email).first()

            if existing_candidate:
                messages.warning(request, f"Candidate with email {email} already exists.")
    # Render the form again with the filled data to give user feedback
                return render(request, 'add_candidate.html', {'form': form})

            

            candidate = form.save(commit=False)
            candidate.user = request.user
            candidate.source = 'recruiter'

            candidate.save()
            return redirect('candidates')
    else:
        form = CandidateForm()
    return render(request, 'add_candidate.html', {'form': form})






def edit_candidate(request, candidate_id):
    form = None
    candidate = get_object_or_404(Candidate, id=candidate_id)
    if request.method == 'POST':
        form = CandidateForm(request.POST, request.FILES, instance=candidate)
        if not form.is_valid():
                print(form.errors)

        if form.is_valid():
            form.instance.source = 'recruiter' 
            form.instance.user = request.user
            form.save()
            print("Form saved successfully!")
            return redirect('candidates')
        else:
            print("Form is invalid!") 
    else:
        form = CandidateForm(instance=candidate)
    return render(request, 'edit_candidate.html', {'form': form})

from django.contrib.auth.decorators import login_required, user_passes_test

@login_required
@user_passes_test(lambda u: u.is_superuser)
def delete_candidate(request):
    if request.method == 'POST':
        candidate_id = request.POST.get('candidate_id')
        candidate = get_object_or_404(Candidate, id=candidate_id)
        candidate.delete()
        return redirect('candidates')

from django.shortcuts import render, get_object_or_404
from .models import Candidate

def candidate_details(request, candidate_id):
    candidate = get_object_or_404(Candidate, pk=candidate_id)
    context = {'candidate': candidate}
    return render(request, 'candidate_details.html', context)

from interviews.models import Interview
from django.shortcuts import render, redirect
from .forms import JobSubmissionForm
from candidates.models import Candidate
from jobs.models import JobSubmission
from django.contrib import messages

def submit_candidate_to_job(request, candidate_id):
    candidate = Candidate.objects.get(id=candidate_id)
    
    if request.method == 'POST':
        form = JobSubmissionForm(request.POST)
        if form.is_valid():
            # Check for previous submission
            previous_submission = JobSubmission.objects.filter(job=form.cleaned_data['job'], candidate=candidate).first()
            
            if previous_submission:
                # Notify user of previous submission and do not save the new submission
                messages.warning(request, f'This candidate was already submitted to this job on {previous_submission.date_submitted.strftime("%Y-%m-%d")}.')
                return redirect('candidates')
            
            else:
                job_submission = form.save(commit=False)
                job_submission.candidate = candidate
                job_submission.user = request.user 
                if not JobSubmission.objects.filter(candidate=candidate).exists():job_submission.stage = 'Internal'
                job_submission.stage_changed_date = timezone.now().date() 
                job_submission.save()
                messages.success(request, 'Candidate successfully submitted to the job!')
                return redirect('candidates')

    else:
        form = JobSubmissionForm()

    return render(request, 'submit_candidate_to_job.html', {'form': form, 'candidate': candidate})

from .forms import CandidateSubmissionForm
from jobs.models import Job

def submit_candidate_for_job(request, job_id):
    job = Job.objects.get(id=job_id)
    query = request.GET.get('search', '')
    candidates = Candidate.objects.filter(name__icontains=query).order_by('name')  # Assuming the name is the search criterion
    
    # Implement pagination
    paginator = Paginator(candidates, 10)  # Show 10 candidates per page
    page = request.GET.get('page')
    candidates = paginator.get_page(page)

    if request.method == 'POST':
        form = CandidateSubmissionForm(request.POST)
        if form.is_valid():
            candidate = form.cleaned_data['candidate']
            
            # Check for previous submission
            previous_submission = JobSubmission.objects.filter(job=job, candidate=candidate).first()
            
            if previous_submission:
                messages.warning(request, f'This candidate was already submitted to this job on {previous_submission.date_submitted.strftime("%Y-%m-%d")}.')
                return redirect('jobs')  # redirect to the job listing page, adjust if needed
            
            else:
                job_submission = form.save(commit=False)
                job_submission.job = job
                job_submission.user = request.user
                if not JobSubmission.objects.filter(candidate=candidate).exists():job_submission.stage = 'Internal'
                job_submission.stage_changed_date = timezone.now().date() 
                job_submission.save()
                messages.success(request, 'Candidate successfully submitted to the job!')
                return redirect('jobs')  # again, adjust the redirect as necessary

    else:
        form = CandidateSubmissionForm()

    return render(request, 'submit_candidate_for_job.html', {'candidates': candidates, 'job': job})

from django.shortcuts import render, get_object_or_404, redirect
from .forms import UpdateStageForm  
from interviews.models import Interview
from django.utils import timezone
from django.db import transaction
from interviews.models import Interview
from jobs.models import JobSubmission
from jobs.models import JobSubmissionHistory


def update_submission_stage(request, submission_id):
    submission = get_object_or_404(JobSubmission, id=submission_id)

    if request.method == "POST":
        form = UpdateStageForm(request.POST, instance=submission)
        if form.is_valid():
            current_stage = form.cleaned_data['stage']
            if current_stage == "Client Submission":
                submission.date_client_submitted = timezone.now()
            submission.save()

            if submission.stage != current_stage:
                # Create a JobSubmissionHistory record
                JobSubmissionHistory.objects.create(
                    job_submission=submission,
                    stage=current_stage,
                    changed_at=timezone.now()
                )

            # Update interview records, if necessary
            interview_stages = ['L1 Interview', 'L2 Interview', 'L3 Interview']
            if current_stage in interview_stages:
                return redirect('interview_details_form', submission_id=submission.id)
            else:
                submission.stage_changed_date = timezone.localtime(timezone.now()).date()
                submission.save()
                return redirect('job_details', job_id=submission.job.id)

    else:  # This else block will handle the GET request
        form = UpdateStageForm(instance=submission)

    return render(request, 'change_stage.html', {'form': form, 'submission': submission})


from .forms import CVImportForm
from .data_extractors import extract_data_from_cv
from django.contrib import messages

def import_candidate(request):
    if request.method == 'POST':
        form = CVImportForm(request.POST, request.FILES)
        if form.is_valid():
            successful_imports = 0

candidates/templates/candidate_details.html
{% extends 'base.html' %}

{% block title %}Candidate Details{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4723D9;">
  <div class="container">
    <!-- Custom CSS class for styling -->
    <a class="navbar-brand custom-title" style="color: #ffffff; font-weight: bold;"><h3>{{ candidate.name }} <a href="{{ candidate.cv.url }}" target="_blank" class="btn btn-secondary">View CV</a>  <a href="{% url 'submit_candidate_to_job' candidate.id %}" class="btn btn-secondary">
      Submit
    </a></h3></a>

  </div>
</nav>

<div class="container mt-10">
  <div class="row">
    <div class="col-md-7">
      <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="mb-2"><strong>Email:</strong> {{ candidate.email }}</div>
                <div class="mb-2"><strong>Phone:</strong> {{ candidate.phone }}</div>
                <div class="mb-2"><strong>Location:</strong> {{ candidate.location }}</div>
                <div class="mb-2"><strong>Current CTC:</strong> Lacs {{ candidate.current_ctc }} / yr</div>
                <div class="mb-2"><strong>Expected CTC:</strong> Lacs {{ candidate.expected_ctc}} / yr</div>
                <div class="mb-3">
                    <strong>Notice Period:</strong> {{ candidate.notice_period }} days
                    {% if candidate.serving_notice_period %}
                      (Serving)
                    {% else %}
                      (Not Serving)
                    {% endif %}
                </div>
                <div class="mb-2"><strong>Last Working Day:</strong> {{ candidate.last_working_day|default:"N/A" }}</div>
                <div class="mb-2"><strong>Expected Joining:</strong> {{ candidate.expected_joining_date|default:"N/A" }}</div>
              </div>
              <div class="col-md-6">
                <div class="mb-2"><strong>Total Exp:</strong> {{ candidate.total_experience }} yrs</div>
                <div class="mb-2"><strong>Relevant Exp:</strong> {{ candidate.relevant_experience }} yrs</div>
                <div class="mb-2"><strong>Reason for Change:</strong> {{ candidate.reason_for_change|default:"N/A" }}</div>
                <div class="mb-2">
                  <strong>LinkedIn:</strong>
                  {% if candidate.linkedin_url %}
                    <a href="{{ candidate.linkedin_url }}" target="_blank">Visit</a>
                  {% else %}
                    N/A
                  {% endif %}
                </div>
              </div>
            </div>

          

          
          <hr>
          <h5><strong>Recruiter Notes:</strong></h5>
          <p>{{ candidate.recruiter_notes|default:"No notes available." }}</p>
          <hr>


        </div>
      </div>
    </div>
    <div class="col-md-5">
      <!-- Candidate Timeline -->
      <div class="card">
        <div class="card-header bg-secondary text-white">
          <h3>Timeline</h3>
        </div>
        <ul class="list-group list-group-flush">
          <!-- You can loop through candidate activities here -->
          <li class="list-group-item">
            <strong>Sourced</strong> 
            <br>
            <strong>Date:</strong> {{ candidate.created_at|date:"Y-m-d" }}
          </li>
          
          <li class="list-group-item">
            <strong>Submitted</strong>
            <ul>
              {% for submission in candidate.jobsubmission_set.all %}
                <li>
                  <strong>Date:</strong> {{ submission.date_submitted|date:"Y-m-d" }} {{ submission.job.job_title }}
                </li>
              {% empty %}
                <li>No submissions</li>
              {% endfor %}
            </ul>
          </li>
          
          
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock %}

candidates/templates/candidates.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}Candidates{% endblock %}

{% block content %}
<style>
  /* Your existing CSS for the header */
  .navbar {
    /* Your header styles here */
    /* ... */
    
    /* Add margin to the left side equal to the base.html navbar width */
    margin-left: 68px; /* Adjust as needed to match the base.html navbar width */
  }
</style>

<header class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #4723D9;">
  <!-- Add these lines to the <head> section of your base.html -->



  <div class="container">
    <a class="navbar-brand custom-title" style="color: #ffffff; font-weight: bold;">Candidates</a>
    
    <form method="GET" action="{% url 'candidates' %}" class="form-inline ml-auto">
      <div class="form-group d-flex align-items-center">

        <!-- Existing search field -->
        <input type="text" name="q" class="form-control" placeholder="Search name" value="{{ search_query }}">


        <!-- Date range filter -->
        <input type="text" id="dateRange" name="date_range" class="form-control ml-2" placeholder="Select Date Range" value="{{ date_range }}">


        <!-- New recruiter filter field -->
        <input type="text" name="recruiter" class="form-control ml-2" value="{{ recruiter }}" placeholder="Recruiter Name">

        <!-- New source filter dropdown -->
        <select name="source_filter" class="form-control ml-2">
          <option value="" {% if source_filter == '' %}selected{% endif %}>CV Source</option>
          <option value="sourced" {% if source_filter == 'sourced' %}selected{% endif %}>Sourced</option>
          <option value="incoming" {% if source_filter == 'incoming' %}selected{% endif %}>Incoming</option>
        </select>

        <!-- Existing search button -->
        {% if search_query %}
        <a href="{% url 'candidates' %}" class="clear-search ml-2"><i class="fas fa-times-circle"></i></a>
        {% endif %}
        <button type="submit" class="btn btn-light font-weight-bold ml-2">Filter</button>
        <a href="{% url 'candidates' %}" class="btn btn-light font-weight-bold ml-2">Clear</a>

      </div>

    </form>
    <div class="ml-2">
      <a href="{% url 'import_candidate' %}" class="btn btn-light font-weight-bold">Import Candidate</a>
      <a href="{% url 'add_candidate' %}" class="btn btn-light font-weight-bold ml-2">Add Candidate</a>
    </div>

  </div>
</header>

<div class="modal fade" id="importResultModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Results</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{{ successful_imports }} CV(s) imported successfully.</p>
        <p>{{ existing_candidates }} already exist.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<main class="table-container" style="margin-top: 70px;">
  {% if candidates %}
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-dark" style="background-color: #ffffff; color: #070707;">
          <tr>
            <th>Created </th>
            <th>Source </th>
            <th>Recruiter</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>City</th>
            <th>CV</th>
            <th><i class="fas fa-share-alt"></i></th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for candidate in candidates %}
            <tr id="candidate-{{ candidate.id }}">
              <td>{{ candidate.created_at|date:"d-m" }}</td>
              <td>{{ candidate.get_source_display }}</td>
              <td>{{ candidate.user.name|get_first_name }}</td>
              <td><a href="{% url 'candidate_details' candidate.id %}"><strong>{{ candidate.name }}</strong></a></td>
              <td>{{ candidate.email }}</td>
              <td>{{ candidate.phone }}</td>
              <td>{{ candidate.location }}</td>
              <td>
                {% if candidate.cv %}
                  <a href="{{ candidate.cv.url }}" target="_blank" class="btn btn-info btn-sm" aria-label="View CV">
                    <i class="fas fa-file-pdf" aria-hidden="true"></i> <!-- Replace with PDF icon or any suitable icon -->
                  </a>
                {% else %}
                  <span class="text-muted">No CV Available</span>
                {% endif %}
              </td>

              <td>
                <a href="{{ candidate.linkedin_url }}" target="_blank" title="LinkedIn Profile" class="linkedin-icon">
                    <i class="fab fa-linkedin ml-2"></i>
                </a>
              </td>

              <td>
                <a href="{% url 'edit_candidate' candidate.id %}" class="btn btn-sm btn-primary" aria-label="Edit Candidate">
                  <i class="fas fa-edit" aria-hidden="true"></i> <!-- Replace with Edit icon or any suitable icon -->
                </a>
                <a href="{% url 'submit_candidate_to_job' candidate.id %}" class="btn btn-sm btn-success" aria-label="Submit Candidate">
                  Submit
                </a>
                <form action="{% url 'delete_candidate' %}" method="POST" class="d-inline">
                  {% csrf_token %}
                  <input type="hidden" name="candidate_id" value="{{ candidate.id }}">
                  <button type="submit" class="btn btn-sm btn-danger {% if not request.user.is_superuser %}disabled{% endif %}" aria-label="Delete Candidate">
                    <i class="fas fa-trash" aria-hidden="true"></i> <!-- Replace with Delete icon or any suitable icon -->
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <div class="alert alert-info" role="alert">
      No candidates found.
    </div>
  {% endif %}


</main>

<!-- Pagination Controls -->
<div class="pagination justify-content-center">
  <ul class="pagination">
    {% for i in candidates.paginator.page_range %}
      {% if candidates.number == i %}
        <li class="page-item active"><a class="page-link">{{ i }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</div>
<!-- End of Pagination Controls -->

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>


<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function () {

    flatpickr("#dateRange", {
        mode: "range",
        dateFormat: "Y-m-d",
    });
  });
</script>





{% endblock %}

candidates/templates/change_stage.html
{% extends 'base.html' %}

{% block title %}Change Candidate status{% endblock %}

{% block content %}
<style>
    /* Page Styles */
    body {
        font-family: Arial, sans-serif;
    }

    h1 {
        text-align: center;
        color: #333;
        margin-bottom: 20px;
    }

    /* Form Styles */
    form {
        width: 60%;
        margin: 40px auto;
        box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
        padding: 20px;
        border-radius: 5px;
    }

    label {
        display: block;
        margin-bottom: 8px;
        font-weight: bold;
    }

    input[type="text"], 
    input[type="datetime-local"], 
    input[type="date"], 
    select {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        padding: 10px 15px;
        background-color: #007BFF;  /* Changing color for differentiation */
        border: none;
        color: white;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Candidate Stage</button>
</form>
{% endblock %}

candidates/templates/import_candidate.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4723D9;">
    <div class="container">
      <!-- Custom CSS class for styling -->
      <a class="navbar-brand custom-title" style="color: #ffffff; font-weight: bold;">Import Candidate</a>

    </div>
  </nav>
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-primary mb-3">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Upload a CV  </h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.as_p }}
                        </div>
                        <div class="d-flex justify-content-end">
                          <button type="submit" class="btn btn-success">Import</button>
                          <div class="mx-2"></div> <!-- Empty div with margin -->
                          <a href="{% url 'candidates' %}" class="btn btn-danger">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}