AA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('', include('clients.urls')),
    path('', include('jobs.urls')),
    path('', include('candidates.urls')),
    path('', include('dashboard.urls')),
    path('', include('reports.urls')),
    path('', include('interviews.urls')),
    path('', include('emailclient.urls')),
    path('', include('naukri.urls')),
    path('', include('settings.urls')),
    path('', include('jobportal.urls')),
]

jobs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('jobs/', views.jobs, name='jobs'),
    path('jobs/add/', views.add_job, name='add_job'),
    path('jobs/edit/<int:job_id>/', views.edit_job, name='edit_job'),
    path('jobs/delete/', views.delete_job, name='delete_job'),
    path('jobs/details/<int:job_id>/', views.job_details, name='job_details'),
    path('jobs/details/<int:job_id>/export-excel/', views.export_job_details_to_excel, name='export_job_details_to_excel'),
    path('jobs/<int:job_id>/', views.view_job, name='view_job'),





]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/models.py
from django.db import models
from clients.models import Client
from candidates.models import Candidate
from django.utils import timezone 


class Job(models.Model):
    JOB_TYPE_CHOICES = [
        ('FT', 'FT'),
        ('Cont', 'Con'),
        ('C2H', 'C2H'),
    ]
    JOB_STATUS_CHOICES = [
        ('Open', 'Open'),
        ('Closed', 'Closed'),
        ('Hold', 'Hold'),
        ('Upcoming', 'Upcoming'),
    ]
    MODE_CHOICES = [
        ('Hybrid', 'Hybrid'),
        ('Remote', 'Remote'),
        ('Onsite', 'Onsite'),
    ]
    PRIORITY_CHOICES = [
        ('High', 'High'),
        ('Medium', 'Medium'),
        ('Low', 'Low'),
    ]
    id = models.AutoField(primary_key=True)
    job_title = models.CharField(max_length=100)
    job_description = models.TextField()
    job_notes = models.TextField()
    job_location = models.CharField(max_length=100)
    job_mode = models.CharField(max_length=20, choices=MODE_CHOICES)
    job_status = models.CharField(max_length=20, choices=JOB_STATUS_CHOICES, default='Open')  
    job_work_hours = models.TextField()
    job_type = models.CharField(max_length=20, choices=JOB_TYPE_CHOICES)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    job_priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    job_attachment = models.FileField(upload_to='job_attachments/', blank=True, null=True)
    job_minimum_experience = models.PositiveIntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    candidates = models.ManyToManyField(Candidate, through='JobSubmission')

    def __str__(self):
        return self.job_title



    
from user_management.models import CustomUser

from jobs.models import Job
class JobSubmission(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    date_submitted = models.DateTimeField(auto_now_add=True)
    date_client_submitted = models.DateTimeField(blank=True, null=True)
    previous_stage = models.CharField(max_length=255, blank=True, null=True)
    
    class Meta:
        unique_together = ('job', 'candidate') 
    
    STAGE_CHOICES = [
        ('Internal', 'Internal'),
        ('Client Submission', 'Client Submission'),
        ('QC Reject', 'QC Reject'),
        ('L1 Interview', 'L1 Interview'),
        ('L2 Interview', 'L2 Interview'),
        ('L3 Interview', 'L3 Interview'),
        ('Interview Reject', 'Interview Reject'),
        ('Shortlisted', 'Shortlisted'),
        ('Joined', 'Joined')
    ]
    
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='Internal')
    stage_changed_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.candidate.name}"



from django.shortcuts import redirect, get_object_or_404
from .models import JobSubmission

def update_submission_stage(request, submission_id, stage):
    print(f"Updating stage for submission ID {submission_id} to {stage}")
    submission = get_object_or_404(JobSubmission, id=submission_id)
    if submission.stage != stage:  # Check if the stage is actually changing
        print(f"Stage is changing from {submission.stage} to {stage}")
        submission.stage = stage
        submission.save()
        JobSubmissionHistory.objects.create(
            job_submission=submission,
            stage=stage,
            changed_at=timezone.now()  # Record the current time
        )
    return redirect('job_details', job_id=submission.job.id)


from django.db import models
from django.utils import timezone

class JobSubmissionHistory(models.Model):
    job_submission = models.ForeignKey(JobSubmission, related_name='histories', on_delete=models.CASCADE)
    stage = models.CharField(max_length=20)
    changed_at = models.DateTimeField()
    

    def __str__(self):
        return f"Changed to {self.stage} at {self.changed_at}"
    

jobs/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Job, Client
from urllib.parse import urlencode


class JobForm(forms.ModelForm):



    class Meta:
        model = Job
        fields = '__all__'
        widgets = {
            'job_status': forms.Select(choices=Job.JOB_STATUS_CHOICES),
            'job_mode': forms.Select(choices=Job.MODE_CHOICES),
            'job_type': forms.Select(choices=Job.JOB_TYPE_CHOICES),  
            'job_priority': forms.Select(choices=Job.PRIORITY_CHOICES),
            

        }

        

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)

        # Exclude the 'candidates' field from the form
        self.fields.pop('candidates')

    def clean_job_attachment(self):
        job_attachment = self.cleaned_data.get('job_attachment', False)
        if job_attachment:
            filename = job_attachment.name
            if not filename.endswith(('.doc', '.docx', '.pdf')):
                raise ValidationError("Invalid file format. Please upload a Word or PDF document.")
        return job_attachment
    



class JobFilterForm(forms.Form):
    job_status = forms.ChoiceField(choices=[('','Select Status')]+list(Job.JOB_STATUS_CHOICES), required=False)
    job_priority = forms.ChoiceField(choices=[('','Select Priority')]+list(Job.PRIORITY_CHOICES), required=False)
    client = forms.ModelChoiceField(queryset=Client.objects.all(), required=False, empty_label="Select Client")

    def urlencode(self):
        data = self.cleaned_data
        query_pairs = []
        for name, value in data.items():
            if value:
                query_pairs.append((name, str(value)))
        return urlencode(query_pairs)

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse  # Add this import statement
from .models import Job, Client
from .forms import JobForm, JobFilterForm
from django.core.paginator import Paginator
from urllib.parse import urlencode
from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test

def jobs(request):
    jobs = Job.objects.all().order_by('-date_added')
    form = JobFilterForm(request.GET)

    if form.is_valid():
        status_filter = form.cleaned_data['job_status']
        priority_filter = form.cleaned_data['job_priority']
        client_filter = form.cleaned_data['client']

        if status_filter:
            jobs = jobs.filter(job_status=status_filter)
        if priority_filter:
            jobs = jobs.filter(job_priority=priority_filter)
        if client_filter:
            jobs = jobs.filter(client=client_filter)
    else:
        form = JobFilterForm()
        jobs = Job.objects.all()
    
    
    # Paginate the jobs
    paginator = Paginator(jobs, 8)  # Show 10 jobs per page (you can change this number)
    page_number = request.GET.get('page')
    jobs_page = paginator.get_page(page_number)

    context = {
        'jobs': jobs_page,  # Use the paginated jobs queryset
        'filter_form': form,
    }
    return render(request, 'jobs.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def edit_job(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES, instance=job)
        if form.is_valid():
            form.save()
            return redirect('jobs')
    else:
        form = JobForm(instance=job)
    return render(request, 'edit_job.html', {'form': form, 'job': job})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def delete_job(request):
    if request.method == 'POST':
        job_id = request.POST.get('job_id')
        job = get_object_or_404(Job, id=job_id)
        job.delete()
        return redirect('jobs')
    else:
        return redirect('jobs')

@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)  # add request.FILES here
        if form.is_valid():
            form.save()
            return redirect('jobs')
    else:
        form = JobForm()
    context = {'form': form}
    return render(request, 'add_job.html', context)

from django.shortcuts import render, get_object_or_404
from .models import Job, JobSubmission
from candidates.models import Candidate  
from django.utils import timezone

def job_details(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    
    all_submissions = JobSubmission.objects.filter(job=job)
    total_subs = all_submissions.count()
    
    # Count of Client Submissions
    client_submission_stages = [
    'Client Submission', 
    'L1 Interview', 
    'L2 Interview', 
    'L3 Interview', 
    'Shortlisted', 
    'Interview Reject', 
    'Joined'
]
    

    client_submissions = all_submissions.filter(stage__in=client_submission_stages).count()

    interview_stages = [
    'L1 Interview', 
    'L2 Interview', 
    'L3 Interview', 
    'Shortlisted', 
    'Interview Reject', 
    'Joined'
]
    # Count of Total Interviews
    total_interviews = all_submissions.filter(stage__in=interview_stages).values('candidate').distinct().count()
    
    # Count of Total shortlist
    shortlist_stages = [

    'Shortlisted', 
    'Joined'
    ]

    total_shortlist = all_submissions.filter(stage__in=shortlist_stages).values('candidate').distinct().count()

    # Count of Total Joining
    joinings_stages = [
    'Joined'
    ]

    total_joinings = all_submissions.filter(stage__in=joinings_stages).values('candidate').distinct().count()

    qc_rejects = all_submissions.filter(stage='QC Reject').count()
    interview_rejects = all_submissions.filter(stage='Interview Reject').count()

    stages = {choice[0]: [] for choice in JobSubmission.STAGE_CHOICES}
    
    for submission in all_submissions:
        stages[submission.stage].append({
            'candidate': submission.candidate,
            'submission_id': submission.id
        })

    days_open = (timezone.now() - job.date_added).days + 1 
    context = {
        'job': job,
        'days_open': days_open,
        'stages': stages,
        'total_subs': total_subs,
        'client_submissions': client_submissions,  
        'total_interviews': total_interviews,       
        'total_shortlist': total_shortlist,
        'total_joinings': total_joinings,
        'qc_rejects': qc_rejects,
        'interview_rejects': interview_rejects
    }
    
    return render(request, 'job_details.html', context)


import pandas as pd
from django.http import HttpResponse
from io import BytesIO

def export_job_details_to_excel(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    all_submissions = JobSubmission.objects.filter(job=job)

    # Calculate the summary values
    total_subs = all_submissions.count()
    qc_rejects = all_submissions.filter(stage='QC Reject').count()
    client_submission_stages = ['Client Submission', 'L1 Interview', 'L2 Interview', 'L3 Interview', 'Shortlisted', 'Interview Reject', 'Joined']
    client_submissions = all_submissions.filter(stage__in=client_submission_stages).count()
    interview_stages = ['L1 Interview', 'L2 Interview', 'L3 Interview', 'Shortlisted', 'Interview Reject', 'Joined']
    total_interviews = all_submissions.filter(stage__in=interview_stages).values('candidate').distinct().count()
    interview_rejects = all_submissions.filter(stage='Interview Reject').count()
    shortlist_stages = ['Shortlisted', 'Joined']
    total_shortlist = all_submissions.filter(stage__in=shortlist_stages).values('candidate').distinct().count()
    joinings_stages = ['Joined']
    total_joinings = all_submissions.filter(stage__in=joinings_stages).values('candidate').distinct().count()

    # Create a Pandas DataFrame for the summary
    summary_data = {
        'Metric': ['Total Sourced', 'Screening Rejects', 'Candidates Submitted', 'Interviews Scheduled', 'Interview Rejects', '# Shortlist', 'Joinings'],
        'Value': [total_subs, qc_rejects, client_submissions, total_interviews, interview_rejects, total_shortlist, total_joinings]
    }
    summary_df = pd.DataFrame(summary_data)

    # Create a Pandas DataFrame for candidate details
    candidate_data = []
    for submission in all_submissions:
        # Convert timezone-aware datetimes to timezone-unaware datetimes
        date_submitted = submission.date_submitted.date() if submission.date_submitted else None
        date_client_submitted = submission.date_client_submitted.date() if submission.date_client_submitted else None


        candidate_data.append([
            submission.candidate.name,
            submission.stage,
            date_submitted,
            date_client_submitted,
        ])

    candidate_df = pd.DataFrame(candidate_data, columns=['Candidate Name', 'Stage', 'Submission Date', 'Client Submission Date'])

    # Create an Excel writer object
    output = BytesIO()

    # Create a Pandas Excel writer using XlsxWriter as the engine
    writer = pd.ExcelWriter(output, engine='xlsxwriter')

    # Write summary data to the Excel file
    summary_df.to_excel(writer, sheet_name='Job Summary', index=False)

    # Write candidate details data to the Excel file
    candidate_df.to_excel(writer, sheet_name='Candidate Details', index=False)

    # Get the xlsxwriter workbook and worksheet objects
    workbook = writer.book
    worksheet = writer.sheets['Job Summary']

    # Add comments with summary data to the Job Summary sheet
    for i, value in enumerate(summary_df['Value']):
        worksheet.write_comment(i + 1, 1, f'Value: {value}')

    # Save the Pandas Excel writer to the BytesIO object
    writer._save()

    # Prepare the response for file download
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = f'attachment; filename={job.job_title}_details.xlsx'
    output.seek(0)
    response.write(output.read())

    return response


from django.shortcuts import render, get_object_or_404
from .models import Job


def view_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    return render(request, 'view_job.html', {'job': job})

jobs/templates/add_job.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Add Job{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4723D9;">
    <div class="container">
      <!-- Custom CSS class for styling -->
      <a class="navbar-brand custom-title" style="color: #ffffff; font-weight: bold;">Add Job</a>
  
    </div>
  </nav>
<div class="container my-4">


    {% if messages %}
    <div class="mb-3">
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <form method="post" enctype="multipart/form-data" class="needs-validation bg-light p-3 rounded shadow" novalidate>
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <!-- Fields for the first column -->
                <div class="form-group mb-1">
                    <label for="{{ form.job_title.id_for_label }}">Job Title</label>
                    {{ form.job_title|add_class:"form-control" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_location.id_for_label }}">Job Location</label>
                    {{ form.job_location|add_class:"form-control" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_work_hours.id_for_label }}">Job Work Hours</label>
                    {{ form.job_work_hours|add_class:"form-control" |attr:"rows:1" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_mode.id_for_label }}">Job Mode</label>
                    {{ form.job_mode|add_class:"form-control" }}
                </div>
            </div>
            <div class="col-md-6">
                <!-- Fields for the second column -->
                <div class="form-group mb-1">
                    <label for="{{ form.client.id_for_label }}">Client</label>
                    {{ form.client|add_class:"form-control" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_status.id_for_label }}">Job Status</label>
                    {{ form.job_status|add_class:"form-control" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_type.id_for_label }}">Job Type</label>
                    {{ form.job_type|add_class:"form-control" }}
                </div>
                <div class="form-group mb-1">
                    <label for="{{ form.job_priority.id_for_label }}">Job Priority</label>
                    {{ form.job_priority|add_class:"form-control" }}
                </div>

            </div>

        </div>
        
        <!-- Full-width field for Job Description -->
        <div class="form-group mb-2">
            <label for="{{ form.job_description.id_for_label }}">Job Description</label>
            {{ form.job_description|add_class:"form-control" |attr:"rows:2" }}
        </div>
        <div class="form-group mb-2">
            <label for="{{ form.job_notes.id_for_label }}">Job Notes</label>
            {{ form.job_notes|add_class:"form-control" |attr:"rows:2" }}
        </div>
        <div class="form-group mb-2">
          <label for="{{ form.job_attachment.id_for_label }}">Job Attachment</label>
          {{ form.job_attachment|add_class:"form-control-file" }}
      </div>
      <div class="form-group mb-1">
        <label for="{{ form.minimum_experience.id_for_label }}">Minimum Experience (in years)</label>
        {{ form.job_minimum_experience|add_class:"form-control" }}
    </div>


    

        <div class="d-flex justify-content-between mt-2">
            <button type="submit" class="btn btn-success">Add Job</button>
            <a href="{% url 'jobs' %}" class="btn btn-danger">Back to jobs list</a>
        </div>
    </form>
</div>
{% endblock %}

jobs/templates/edit_job.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Edit Job{% endblock %}

{% block content %}


<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4723D9;">
  <div class="container">
    <!-- Custom CSS class for styling -->
    <a class="navbar-brand custom-title" style="color: #ffffff; font-weight: bold;">Edit Job</a>

  </div>
</nav>
<div class="container my-4">


  {% if messages %}
  <div class="mb-3">
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
          {{ message }}
      </div>
      {% endfor %}
  </div>
  {% endif %}

  <form method="post" enctype="multipart/form-data" class="needs-validation bg-light p-3 rounded shadow" novalidate>
      {% csrf_token %}
      <div class="row">
          <div class="col-md-6">
              <!-- Fields for the first column -->
              <div class="form-group mb-1">
                  <label for="{{ form.job_title.id_for_label }}">Job Title</label>
                  {{ form.job_title|add_class:"form-control" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_location.id_for_label }}">Job Location</label>
                  {{ form.job_location|add_class:"form-control" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_work_hours.id_for_label }}">Job Work Hours</label>
                  {{ form.job_work_hours|add_class:"form-control" |attr:"rows:1" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_mode.id_for_label }}">Job Mode</label>
                  {{ form.job_mode|add_class:"form-control" }}
              </div>
          </div>
          <div class="col-md-6">
              <!-- Fields for the second column -->
              <div class="form-group mb-1">
                  <label for="{{ form.client.id_for_label }}">Client</label>
                  {{ form.client|add_class:"form-control" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_status.id_for_label }}">Job Status</label>
                  {{ form.job_status|add_class:"form-control" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_type.id_for_label }}">Job Type</label>
                  {{ form.job_type|add_class:"form-control" }}
              </div>
              <div class="form-group mb-1">
                  <label for="{{ form.job_priority.id_for_label }}">Job Priority</label>
                  {{ form.job_priority|add_class:"form-control" }}
              </div>

          </div>
      </div>
      
      <!-- Full-width field for Job Description -->
      <div class="form-group mb-2">
          <label for="{{ form.job_description.id_for_label }}">Job Description</label>
          {{ form.job_description|add_class:"form-control" |attr:"rows:2" }}
      </div>
      <div class="form-group mb-2">
        <label for="{{ form.job_notes.id_for_label }}">Job Notes</label>
        {{ form.job_notes|add_class:"form-control" |attr:"rows:2" }}
    </div>
      <div class="form-group mb-2">
        <label for="{{ form.job_attachment.id_for_label }}">Job Attachment</label>
        {{ form.job_attachment|add_class:"form-control-file" }}
    </div>
    <div class="form-group mb-1">
        <label for="{{ form.minimum_experience.id_for_label }}">Minimum Experience (in years)</label>
        {{ form.job_minimum_experience|add_class:"form-control" }}
    </div>

    

      <div class="d-flex justify-content-between mt-2">
          <button type="submit" class="btn btn-success">Edit Job</button>
          <a href="{% url 'jobs' %}" class="btn btn-danger">Back to jobs list</a>
      </div>
  </form>
</div>
{% endblock %}

jobs/templates/job_details.html
{% extends 'base.html' %}

{% block title %}Job Detail{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row enhanced-row bg-light py-2 px-4  align-items-center shadow-sm" style="border-top: 2px solid black; border-bottom: 2px solid black; margin-bottom: 2px;">
        <!-- Job title and client to the left -->
        <div class="col-md-2 d-flex align-items-center">
            <h6 class="mb-0 spacer-right text-primary"><strong>{{ job.job_title }}|</strong></h6>
            <span class="text-muted spacer-left"><strong>|{{ job.client.code }}</strong></span>
        </div>
        <!-- Metrics centered -->
        <div class="col-md-9 d-flex align-items-center justify-content-center">
            <span class="metric spacer-right"><i class="fas fa-users"></i> <strong>Sourced:</strong> <strong>{{ total_subs }}</strong></span>|
            <span class="metric spacer-right text-danger"><i class="fas fa-times"></i> <strong>QC Rejects:</strong> <strong>{{ qc_rejects }}</strong></span>|
            <span class="metric spacer-right text-success"><i class="fas fa-paper-plane"></i> <strong>Submitted:</strong> <strong>{{ client_submissions }}</strong></span>|
            <span class="metric spacer-right text-warning"><i class="fas fa-comments"></i> <strong>Interviews:</strong> <strong>{{ total_interviews }}</strong></span>|
            <span class="metric spacer-right text-danger"><i class="fas fa-thumbs-down"></i> <strong>Int. Rejects:</strong> <strong>{{ interview_rejects }}</strong></span>|
            <span class="metric spacer-right text-info"><i class="fas fa-star"></i> <strong>Shortlist:</strong> <strong>{{ total_shortlist }}</strong></span>|
            <span class="metric spacer-right text-success"><i class="fas fa-user-check"></i> <strong>Joinings:</strong> <strong>{{ total_joinings }}</strong></span>

        </div>
        <!-- Open days and jobs button to the right -->
        <div class="col-md-1 d-flex align-items-center justify-content-end">
            <span class="text-primary spacer-right mr-2"><i class="fas fa-clock"></i> {{ days_open }} Days</span>
            <a href="{% url 'export_job_details_to_excel' job_id=job.id %}" class="btn btn-sm btn-success enhanced-btn" style="margin-left: 15px;">
                Export
            </a>
        </div>
    </div>
    
    <div class="row">
        {% for stage, candidate_infos in stages.items %}
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header bg-primary text-white">{{ stage }}</div>
                    <div class="card-body">
                        {% if candidate_infos %}
                            <table class="table table-borderless">
                                <tbody>
                                    {% for candidate_info in candidate_infos %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'candidate_details' candidate_id=candidate_info.candidate.id %}" class="black-link">{{ candidate_info.candidate.name }}</a>
                                              </td>
                                              <style>
                                                .black-link {
                                                  color: black; /* Set the desired text color */
                                                  font-weight: bold;
                                                }
                                              </style>
                                            <td>
                                                <!-- CV Icon linked to the CV's URL -->
                                                <a href="{{ candidate_info.candidate.cv.url }}" target="_blank" title="View CV">
                                                    <i class="fas fa-file-alt ml-2 custom-icon-color"></i>
                                                  </a>
                                            </td>
                                            <style>
                                                .custom-icon-color {
                                                  color: red; /* Change this to your desired color */
                                                }
                                              </style>
                                            <td>
                                                <!-- LinkedIn Icon linked to the LinkedIn profile URL -->
                                                <a href="{{ candidate_info.candidate.linkedin_url }}" target="_blank" title="LinkedIn Profile">
                                                    <i class="fab fa-linkedin ml-2"></i>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'update_submission_stage' submission_id=candidate_info.submission_id %}" class="change-stage-btn" title="Change Stage">
                                                    <i class="fas fa-exchange-alt custom-icon-color"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% else %}
                            <p>No Candidates Here Currently.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
    

    
    
    
    
    
{% endblock %}

jobs/templates/view_job.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Job Details{% endblock %}

{% block content %}

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #4723D9;">
    <div class="container">
      <!-- Custom CSS class for styling -->
      <a class="navbar-brand text-white font-weight-bold" href="#">{{ job.job_title }}</a>
    </div>
  </nav>

<!-- Job Details Section -->
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="mb-2"><strong>Location:</strong> {{ job.job_location }}</p>
                            <p class="mb-2"><strong>Experience:</strong> {{ job.job_minimum_experience }}+ Years</p>
                            <p class="mb-2"><strong>Job Type:</strong> {{ job.get_job_type_display }}</p>
                        </div>
                        <div class="col-md-6">
                            <p class="mb-2"><strong>Job Mode:</strong> {{ job.job_mode }}</p>
                            <p class="mb-2"><strong>Job Status:</strong> {{ job.job_status }}</p>
                            <p class="mb-2"><strong>Priority:</strong> {{ job.get_job_priority_display }}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <p><strong>Work Hours:</strong> {{ job.job_work_hours }}</p>
                            <p><strong>Client:</strong> {{ job.client }}</p>
                            <p><strong>Date Added:</strong> {{ job.date_added }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <hr>

    <!-- Job Description -->
    <div class="row mt-4">
        <div class="col-md-8">
            <h2>Job Description</h2>
            <p>{{ job.job_description }}</p>
        </div>
    </div>

    <!-- Job Notes -->
    <div class="row mt-4">
        <div class="col-md-8">
            <h2>Job Notes</h2>
            <p>{{ job.job_notes }}</p>
        </div>
    </div>
</div>

{% endblock %}